### ISSUE TITLE
General away mode

### ISSUE THREAD

**Issue by BasTijs** [asev/homeassistant-uponor#15]
I have a question about how to control whole house climate. In the app I can set the whole system to away, but if I call the climate service in HA this has to be set individual (also not sure if it works). Is it possible to set general away mode from home assistant?

**Comment by thecem** [comment]
There is no implementation of presence detection, or an away mode of the uponor app, even the away mode of the app is not in. You will achive this with:

https://www.home-assistant.io/integrations/climate/#service-climateturn_on

```
automation:
  trigger:
    platform: time
    at: "07:15:00"
  action:
    - service: climate.turn_off
      data:
        entity_id: 'climate.kitchen,climate.bathroom'
```

for presence detection you cloud use:

https://www.home-assistant.io/integrations/#presence-detection
