### ISSUE TITLE
Humidity 

### ISSUE THREAD

**Issue by RudyvdRijdt** [asev/homeassistant-uponor#28]
Hi, Is it possible to add the humidity% as an entity

**Comment by thecem** [comment]
Did you tried this:

```
          - entity: climate.wohnzimmer
            attribute: current_temperature
            unit: °C
            state_adaptive_color: true
          - entity: climate.wohnzimmer
            attribute: current_humidity
            unit: '%'
            show_state: true
            state_adaptive_color: true
            y_axis: secondary
        hour24: true
        points_per_hour: 1
        decimals: 1
        name: Thermo
        show:
          extrema: false
          fill: false
          legend: false
          name: false
          icon: false
        font_size: 70
        type: custom:mini-graph-card
```

with the mini-graph-card and the climate.xxx in recorder, you have al details. Otherwise you have the possibility to add a template sensor.

**Comment by asev** [comment]
Hi. This is how I'm doing it:

```
# configuration.yaml

sensor:
  - platform: template
    sensors:
      living_room_humidity:
        friendly_name: "Living Room Humidity"
        unit_of_measurement: "%"
        icon_template: "mdi:water-percent"
        value_template: "{{ states.climate.living_room.attributes.current_humidity }}"
```
