### ISSUE TITLE
Request: Humidity infomation

### ISSUE THREAD

**Issue by arva-zz** [asev/homeassistant-uponor#9]
My thermostats give out humidity information as well. Would it be possible to capture and show this information?

**Comment by thecem** [comment]
![0A5AE0C9-CFE2-4879-9C46-0DB88452BC9A](https://user-images.githubusercontent.com/46648579/95952333-2c3a4980-0df8-11eb-9533-1105195dda05.jpeg)

The humidity information is in the attributes....

**Comment by asev** [comment]
Thanks @thecem for the quick answer.
@arva-zz if you want to have it as separate sensor you can create one
```
sensor:
  - platform: template
    sensors:
      bad_humidity:
        friendly_name: "Bad humidity"
        unit_of_measurement: "%"
        value_template: "{{ states.climate.bad.attributes.current_humidity }}"
```
